### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by ekaj2**

### CODE REVIEW

**Comment by ekaj2** [comment]
Ready for a release?

**Comment by MaximeHerpin** [comment]
Yes :)

**Comment by ekaj2** [comment]
Do you have an error when you crank up the step size for the grease pencil? Like 20?

**Comment by MaximeHerpin** [comment]
Yes, index out of range

**Comment by ekaj2** [comment]
Do you think that is an easy fix?

**Comment by MaximeHerpin** [comment]
I'm not sure but yes, probably

**Comment by ekaj2** [comment]
[Can you fix that before the release.](https://github.com/MaximeHerpin/modular_tree/issues/125)

**Pull request merged**
