### PR TITLE
Force fields

### PR DESCRIPTION
**Pull request by MaximeHerpin**

### CODE REVIEW

**Comment by ekaj2** [comment]
Ooo, conflict!

**Comment by MaximeHerpin** [comment]
How do I solve it ?

**Comment by ekaj2** [comment]
I am almost done...I can teach you sometime...

**Comment by MaximeHerpin** [comment]
Great, thanks !

**Comment by ekaj2** [comment]
I will make a wiki page showing how to resolve conflicts sometime. Will let you know...

Is this something you think is worth another release?

**Comment by MaximeHerpin** [comment]
I will work on the twig improvements now, it shouldn't take too much time so let's wait a little bit :)

**Comment by ekaj2** [comment]
@MaximeHerpin I added a tutorial in the wiki for merge conflicts...let me know if you run into any problems. 

TODO - Add details of what is actually making conflicts.

**Comment by MaximeHerpin** [comment]
Ok great !

**Pull request merged**
